name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:  # Runs on all PRs, no matter the branch

jobs:
  cypress-ui:
    runs-on: ubuntu-latest
    container: cypress/browsers:node-20.18.0-chrome-126-ff-128  # includes Firefox 128 ESR
    strategy:
      matrix:
        browser: [chrome, firefox] # Enable cross browser testing for Github Actions
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # This version will be supported for a while

      - name: Install dependencies
        run: npm install

      - name: Clean Reports Folder
        run: rm -rf cypress/reports || true # Delete reports folder (removes old screenshots, logs etc)

      - name: Run UI Tests in ${{ matrix.browser }}
        env: 
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Get record key from Github secrets for Cypress Cloud runs
        run: npx cypress run --browser ${{ matrix.browser }} --headless --spec "cypress/e2e/ui/*.cy.js" --record --group "UI Tests - ${{ matrix.browser }}"

      - name: Upload UI report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-ui-${{ matrix.browser }} # Generates a report for each browser
          path: cypress/reports/
          retention-days: 7 # Keep files for 7 days instead of the default 90

  cypress-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Clean Reports Folder
        run: rm -rf cypress/reports || true

      - name: Run API Tests 
        env:
          CYPRESS_BOOKING_USERNAME: ${{ secrets.CYPRESS_BOOKING_USERNAME }} # Get API auth login from Github secrets
          CYPRESS_BOOKING_PASSWORD: ${{ secrets.CYPRESS_BOOKING_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} 
        run: npx cypress run --headless --spec "cypress/e2e/api/*.cy.js" --record --group "API Tests"

      - name: Upload API report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-api
          path: cypress/reports/
          retention-days: 7